version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
#  web:
#    build: ./
#    ports:
#      - "8000:8000"
#    command: python3 manage.py runserver 0:8000
#    restart: always
#    volumes:
#      - .:/code
#    depends_on:
#      - db
  celery:
    build: ./
    command: celery -A core worker -l info
    depends_on:
      - redis
  celery-beat:
    build: ./
    command: celery -A core beat -l info
    depends_on:
      - redis
      - celery
  celery-flower:
    build: ./
    command: celery -A core flower --port=5566
    ports:
      - "5566:5566"
    depends_on:
      - redis
      - celery
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
volumes:
  code:
  pgdata: Null
